### ISSUE TITLE
Bug in `createChecksum`

### ISSUE THREAD

**Issue by AArnott** [DesWurstes/Bech32-Csharp#4]
Per [the spec](https://zips.z.cash/zip-0173), the create checksum function should assign polymod like this:

```rb
polymod = bech32_polymod(values + [0,0,0,0,0,0]) ^ 1
```

But in your code, you leave off the ` ^ 1` at the end:

https://github.com/DesWurstes/Bech32-Csharp/blob/7e3ef04e26934f787c81c103a336373ac9bbf8d8/Bech32-Csharp/Bech32-Csharp.cs#L82

**Comment by DesWurstes** [comment]
Done, thanks for the catch
